<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>team.magic-flute</groupId>
        <artifactId>Hercules</artifactId>
        <version>Nemean-Lion-1.0</version>
    </parent>

    <artifactId>Hercules-executor-plugin</artifactId>
    <packaging>pom</packaging>

    <name>Hercules-executor-plugin</name>
    <url>http://maven.apache.org</url>
    <modules>
        <module>Hercules-executor-plugin-common-business</module>
        <module>Hercules-executor-plugin-common-bi</module>
        <module>Hercules-executor-plugin-test</module>
    </modules>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <dependency>
            <groupId>team.magic-flute</groupId>
            <artifactId>Hercules-common</artifactId>
            <version>${hercules.version}</version>
            <!--The executor itself has this dependency, you can enable this for local testing, but you need to add this scope when packaging.-->
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.13.0</version>
                <configuration>
                    <java>
                        <googleJavaFormat>
                            <version>1.7</version>
                            <style>AOSP</style>
                        </googleJavaFormat>
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <id>format</id>
                        <goals>
                            <goal>check</goal>
                            <goal>apply</goal>
                        </goals>
                        <phase>process-sources</phase>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.9.10</version>
                <configuration>
                    <failOnNoGitDirectory>false</failOnNoGitDirectory>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <dateFormat>yyyyMMddHHmmss</dateFormat>
                    <replacementProperties>
                        <replacementProperty>
                            <property>git.branch</property>
                            <token>/</token>
                            <value>-</value>
                        </replacementProperty>
                    </replacementProperties>
                </configuration>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.1</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <outputFile>${project.build.directory}/${project.artifactId}-${git.branch}-${git.commit.time}-${git.dirty}.jar</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
