package team.magic.flute.hercules.manager.dao.po;

import com.baomidou.mybatisplus.annotation.FieldStrategy;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import org.apache.commons.lang3.RandomUtils;
import team.magic.flute.hercules.common.status.TaskStatus;
import team.magic.flute.hercules.manager.entity.cron.CronTaskContext;
import team.magic.flute.hercules.manager.entity.recover.RecoverStrategy;
import team.magic.flute.hercules.manager.util.DateUtil;
import lombok.Data;
import lombok.experimental.Accessors;
import org.apache.commons.codec.digest.DigestUtils;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDateTime;

import static team.magic.flute.hercules.common.global.Constant.TASK_MAX_BUCKET_SIZE;
import static team.magic.flute.hercules.common.status.TaskType.FROM_CRON;

@Data
@Accessors(chain = true)
@TableName(value = "HERCULES_CRON_TASKS", autoResultMap = true)
public class HerculesCronJobs {
    @TableId(value = "JOB_ID")
    private String jobId;
    @TableField(value = "EXECUTOR_REGION")
    private String executorRegion;
    @TableField(value = "PLUGIN_GROUP")
    private String pluginGroup;
    @TableField(value = "PLUGIN_HANDLE")
    private String pluginHandle;
    @TableField(value = "DESCRIPTION")
    private String description;
    @TableField(value = "CRON_EXPRESSION")
    private String cronExpression;
    @TableField(value = "ENABLE")
    private Boolean enable;
    @TableField(value = "BEGIN")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime begin;

    @TableField(value = "END")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime end;

    @TableField(value = "SNAPSHOT")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime snapshot;

    @TableField(value = "CHECKPOINT")
    private String checkpoint;
    /**
     * The context of a scheduling task. Each type of task can
     * have its own context, which is used to determine the actual
     * parameters required for executing the task after successful scheduling.
     * <p>
     * Each time a scheduled task is triggered,
     * it generates an executable task. The context information for
     * this executable task is derived from the content within this context.
     */
    @TableField(value = "CONTEXT",typeHandler = JacksonTypeHandler.class)
    private CronTaskContext context;
    @TableField(value = "SUPPORT_MISFIRE")
    private Boolean supportMisFire;
    @TableField(value = "MISFIRE_PARALLELISM")
    private Integer misFireParallelism;
    @TableField(value = "MAX_RETRY_TIMES")
    private Integer maxRetryTimes;

    /**
     * Asynchronous recovery parameters and context, where these parameters
     * determine the asynchronous recovery strategy for tasks generated by the scheduler.
     */
    @TableField(value = "ASYNC_RECOVER_CONTEXT",typeHandler = JacksonTypeHandler.class)
    private RecoverStrategy asyncRecoverContext;

    @TableField(value = "BUCKET_ID")
    private Integer bucketId;//= RandomUtils.nextInt(1,100);

    @TableField(value = "INSERT_TIME",updateStrategy = FieldStrategy.NEVER)
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime insertTime;

    @TableField(value = "UPDATE_TIME")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime updateTime;

    public HerculesTaskInfo parse2TaskInfo(LocalDateTime nextProcessTime,String updatedContext){
        /*
        * The consideration for crontab here is: since the trigger time of crontab is fixed,
        * using the scheduled task + the next trigger time as the task primary key
        * ensures that the scheduled task will be generated exactly once.
        * For scenarios where the database serves as the task processing foundation
        * (current implementation), this allows the use of primary key constraints.
        * For cases where a message queue is used as the task processing foundation,
        * logic similar to exactly-once delivery + partitioning can be applied to ensure
        * the task is sent only once.
        * */
        String id = DateUtil.formatLocalDateTime2Long(nextProcessTime) + "_" + DigestUtils.md5Hex(getJobId().trim() + DateUtil.formatLocalDateTime2Long(nextProcessTime));
        return new HerculesTaskInfo().setId(id)
                .setSourceId(getJobId())
                .setDesc(getDescription())
                .setExecutorRegion(getExecutorRegion())
                .setFromType(FROM_CRON.name())
                .setContext(updatedContext)
                .setAsyncRecoverContext(getAsyncRecoverContext())
                .setEnable(true)
                .setBucketId(RandomUtils.nextInt(1,TASK_MAX_BUCKET_SIZE))
                .setStatus(TaskStatus.INIT.name())
                .setInsertTime(LocalDateTime.now())
                .setUpdateTime(LocalDateTime.now())
                .setMaxRetryTimes(getMaxRetryTimes())
                .setPluginGroup(pluginGroup)
                .setPluginHandle(pluginHandle);
    }
}
