language: java
jdk:
  - oraclejdk8
docker:
  - docker1.12
build:
  app_version: "mvn -q -Dexec.executable='echo' -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec"
  script:
    - mvn clean install -DskipTests -U
package:
  - type: docker
    docker_file: Dockerfile
    registry_uri: hub.shuyun.com
    image_name: coms/hercules-twelve-labors
    image_tag: ${APP_VERSION}-${TIMESTAMP}
compose:
  - type: service
    service_file: .service.yml