spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&nullCatalogMeansCurrent=true"
    username: "root"
    password: "xxxxxxxxxxxx"


file-storage:
  oss:
    endpoint: "oss-cn-zhangjiakou.aliyuncs.com"
    bucket: "shuyun-cem-qa"
    access: "xx"
    secret: "xx"
    root-path: "hercules/qa/plugin/"
    support-http-download: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
